package com.fieldreport.model;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Objects;
import java.util.UUID;

/**
 * Model class representing a daily field report in the construction/project management system.
 * 
 * This class encapsulates all essential information about work performed in the field,
 * including worker details, project information, weather conditions, and work progress.
 * Each report is uniquely identified and timestamped for tracking purposes.
 * 
 * Key Features:
 * - Automatic UUID generation for unique identification
 * - Timestamp tracking for creation and date management
 * - Comprehensive validation for data integrity
 * - Support for both mandatory and optional fields
 * - JSON-ready structure for data persistence
 * 
 * Usage Examples:
 * <pre>
 * // Create a new report with current date
 * FieldReport report = new FieldReport("John Doe", "Site A", "Bridge Project", 
 *                                       "Sunny", "Foundation work", "No issues");
 * 
 * // Create a report for specific date
 * FieldReport report = new FieldReport(LocalDate.of(2025, 10, 20), "Jane Smith", 
 *                                       "Site B", "Road Project", "Rainy", 
 *                                       "Delayed due to weather", "Resume tomorrow");
 * </pre>
 * 
 * @author Daily Field Report System
 * @version 1.0
 * @since 2025-10-24
 */
public class FieldReport {
    
    /** Unique identifier for the field report - automatically generated UUID */
    private String id;
    
    /** Date of the field work - defaults to current date if not specified */
    private LocalDate date;
    
    /** Timestamp when the report was created in the system */
    private LocalDateTime createdAt;
    
    /** Name of the person submitting the field report */
    private String reporterName;
    
    /** Physical location or site where the work was performed */
    private String location;
    
    /** Name or identifier of the project being worked on */
    private String projectName;
    
    /** Weather conditions during the work period */
    private String weatherConditions;
    
    /** Detailed description of work performed and progress made */
    private String workDescription;
    
    /** Additional notes, issues, or observations (optional field) */
    private String notes;
    
    /**
     * Default constructor for JSON deserialization and object creation.
     * 
     * Automatically generates a unique ID and sets the creation timestamp.
     * Date is set to current date by default but can be modified later.
     */
    public FieldReport() {
        this.id = UUID.randomUUID().toString();
        this.date = LocalDate.now();
        this.createdAt = LocalDateTime.now();
    }
    
    /**
     * Constructs a field report with current date and all mandatory fields.
     * 
     * This constructor creates a report for today's work with all required
     * information. The report ID and creation timestamp are automatically
     * generated by calling the default constructor.
     * 
     * @param reporterName name of the person submitting the report
     * @param location physical site or location where work was performed
     * @param projectName name or identifier of the project
     * @param weatherConditions description of weather conditions during work
     * @param workDescription detailed description of work performed
     * @param notes additional observations or issues (can be null or empty)
     * 
     * @throws IllegalArgumentException if any mandatory field is null or empty
     */
    public FieldReport(String reporterName, String location, String projectName, 
                      String weatherConditions, String workDescription, String notes) {
        this();
        this.reporterName = reporterName;
        this.location = location;
        this.projectName = projectName;
        this.weatherConditions = weatherConditions;
        this.workDescription = workDescription;
        this.notes = notes != null ? notes : "";
    }
    
    /**
     * Constructs a field report with a specific date and all required fields.
     * 
     * This constructor allows creating reports for specific dates (past or future)
     * rather than defaulting to the current date. Useful for backdating reports
     * or planning future work.
     * 
     * @param date the specific date when the field work was/will be performed
     * @param reporterName name of the person submitting the report
     * @param location physical site or location where work was performed
     * @param projectName name or identifier of the project
     * @param weatherConditions description of weather conditions during work
     * @param workDescription detailed description of work performed
     * @param notes additional observations or issues (can be null or empty)
     * 
     * @throws IllegalArgumentException if any mandatory field is null or empty
     */
    public FieldReport(LocalDate date, String reporterName, String location, String projectName, 
                      String weatherConditions, String workDescription, String notes) {
        this(reporterName, location, projectName, weatherConditions, workDescription, notes);
        this.date = date;
    }
    
    // ================= GETTERS AND SETTERS =================
    
    /**
     * Gets the unique identifier for this field report.
     * 
     * @return the UUID string that uniquely identifies this report
     */
    public String getId() {
        return id;
    }
    
    /**
     * Sets the unique identifier for this field report.
     * 
     * Note: This should generally not be called after object creation
     * as the ID is auto-generated and should remain immutable.
     * 
     * @param id the UUID string to set as the unique identifier
     */
    public void setId(String id) {
        this.id = id;
    }
    
    /**
     * Gets the date when the field work was performed.
     * 
     * @return the date of the field work
     */
    public LocalDate getDate() {
        return date;
    }
    
    /**
     * Sets the date when the field work was performed.
     * 
     * @param date the date of the field work
     */
    public void setDate(LocalDate date) {
        this.date = date;
    }
    
    /**
     * Gets the timestamp when this report was created in the system.
     * 
     * @return the creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
    
    /**
     * Sets the timestamp when this report was created in the system.
     * 
     * Note: This is typically set automatically during object creation
     * and should rarely need to be modified manually.
     * 
     * @param createdAt the creation timestamp
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }
    
    /**
     * Gets the name of the person who submitted this field report.
     * 
     * @return the reporter's name
     */
    public String getReporterName() {
        return reporterName;
    }
    
    /**
     * Sets the name of the person who submitted this field report.
     * 
     * @param reporterName the reporter's name
     */
    public void setReporterName(String reporterName) {
        this.reporterName = reporterName;
    }
    
    /**
     * Gets the physical location or site where the field work was performed.
     * 
     * @return the work location
     */
    public String getLocation() {
        return location;
    }
    
    /**
     * Sets the physical location or site where the field work was performed.
     * 
     * @param location the work location
     */
    public void setLocation(String location) {
        this.location = location;
    }
    
    /**
     * Gets the name or identifier of the project being worked on.
     * 
     * @return the project name
     */
    public String getProjectName() {
        return projectName;
    }
    
    /**
     * Sets the name or identifier of the project being worked on.
     * 
     * @param projectName the project name
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    
    /**
     * Gets the weather conditions during the work period.
     * 
     * @return the weather conditions description
     */
    public String getWeatherConditions() {
        return weatherConditions;
    }
    
    /**
     * Sets the weather conditions during the work period.
     * 
     * @param weatherConditions the weather conditions description
     */
    public void setWeatherConditions(String weatherConditions) {
        this.weatherConditions = weatherConditions;
    }
    
    /**
     * Gets the detailed description of work performed and progress made.
     * 
     * @return the work description
     */
    public String getWorkDescription() {
        return workDescription;
    }
    
    /**
     * Sets the detailed description of work performed and progress made.
     * 
     * @param workDescription the work description
     */
    public void setWorkDescription(String workDescription) {
        this.workDescription = workDescription;
    }
    
    /**
     * Gets additional notes, issues, or observations about the field work.
     * 
     * @return the notes (may be empty string if no notes provided)
     */
    public String getNotes() {
        return notes;
    }
    
    /**
     * Sets additional notes, issues, or observations about the field work.
     * 
     * @param notes additional observations (can be null, will be converted to empty string)
     */
    public void setNotes(String notes) {
        this.notes = notes != null ? notes : "";
    }
    
    // ================= OBJECT COMPARISON METHODS =================
    
    /**
     * Compares this field report with another object for equality.
     * 
     * Two field reports are considered equal if they have the same ID,
     * since each report should have a unique identifier.
     * 
     * @param o the object to compare with this field report
     * @return true if the objects are equal, false otherwise
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        FieldReport that = (FieldReport) o;
        return Objects.equals(id, that.id);
    }
    
    /**
     * Returns a hash code value for this field report.
     * 
     * The hash code is based solely on the unique ID field,
     * consistent with the equals() method implementation.
     * 
     * @return a hash code value for this object
     */
    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
    
    /**
     * Returns a string representation of this field report.
     * 
     * Provides a readable format showing all field values, useful for
     * debugging and logging purposes.
     * 
     * @return a string representation of the object
     */
    @Override
    public String toString() {
        return "FieldReport{" +
                "id='" + id + '\'' +
                ", date=" + date +
                ", reporterName='" + reporterName + '\'' +
                ", location='" + location + '\'' +
                ", projectName='" + projectName + '\'' +
                ", weatherConditions='" + weatherConditions + '\'' +
                ", workDescription='" + workDescription + '\'' +
                ", notes='" + notes + '\'' +
                '}';
    }
    
    // ================= VALIDATION METHODS =================
    
    /**
     * Validates that the field report has all required fields populated.
     * 
     * Checks that mandatory fields (reporter name, location, project name,
     * weather conditions, and work description) are not null or empty.
     * The notes field is optional and not validated.
     * 
     * @return true if all required fields are valid, false otherwise
     */
    public boolean isValid() {
        return reporterName != null && !reporterName.trim().isEmpty() &&
               location != null && !location.trim().isEmpty() &&
               projectName != null && !projectName.trim().isEmpty() &&
               workDescription != null && !workDescription.trim().isEmpty();
    }
}